import datetime

# Get current date and time
now = datetime.datetime.now()

# Print various formatted date and time strings
print("Weekday (short):", now.strftime("%a"))
print("Weekday (full):", now.strftime("%A"))
print("Weekday as number (Sunday=0):", now.strftime("%w"))
print("Day of month:", now.strftime("%d"))
print("Month name (short):", now.strftime("%b"))
print("Month name (full):", now.strftime("%B"))
print("Month as number:", now.strftime("%m"))
print("Year (short):", now.strftime("%y"))
print("Year (full):", now.strftime("%Y"))
print("Hour (00-23):", now.strftime("%H"))
print("Hour (00-12):", now.strftime("%I"))
print("AM/PM:", now.strftime("%p"))
print("Minute:", now.strftime("%M"))
print("Second:", now.strftime("%S"))
print("Microsecond:", now.strftime("%f"))
print("UTC offset:", now.strftime("%z"))
print("Timezone:", now.strftime("%Z"))
print("Day number of year:", now.strftime("%j"))
print("Week number of year (Sunday=1):", now.strftime("%U"))
print("Week number of year (Monday=1):", now.strftime("%W"))
print("Local version of date and time:", now.strftime("%c"))
print("Century:", now.strftime("%C"))
print("Local version of date:", now.strftime("%x"))
print("Local version of time:", now.strftime("%X"))
print("Percent character:", now.strftime("%%"))
print("ISO 8601 year:", now.strftime("%G"))
print("ISO 8601 weekday (1-7):", now.strftime("%u"))
print("ISO 8601 week number (01-53):", now.strftime("%V"))
